/*
 * Copyright (c) 2023-2023. Encept Ltd Company, https://encept.co
 * contact: support@encept.co
 */

package co.encept.muqataa

import android.content.Context


class HandleBarCode {



    fun getCountry(c: Context, code: String): String {
        if (code.length >= 3) {
            return when (code.substring(0, 3)) {
                in "450".."459", in "490".."499" -> c.getString(R.string.country_japan)
                "870", in "872".."879" -> c.getString(R.string.country_netherlands)
                in "540".."549" -> c.getString(R.string.country_belgium_luxembourg)
                in "500".."509" -> c.getString(R.string.country_united_kingdom)
                in "060".."139" -> c.getString(R.string.country_united_states)
                in "600".."601" -> c.getString(R.string.country_south_africa)
                in "760".."769" -> c.getString(R.string.country_switzerland)
                in "940".."949" -> c.getString(R.string.country_new_zealand)
                in "778".."779" -> c.getString(R.string.country_argentina)
                in "930".."939" -> c.getString(R.string.country_australia)
                in "900".."919" -> c.getString(R.string.country_austria)
                in "770".."771" -> c.getString(R.string.country_colombia)
                in "300".."379" -> c.getString(R.string.country_france)
                in "400".."440" -> c.getString(R.string.country_germany)
                in "460".."469" -> c.getString(R.string.country_russia)
                in "570".."579" -> c.getString(R.string.country_denmark)
                in "520".."521" -> c.getString(R.string.country_greece)
                in "640".."649" -> c.getString(R.string.country_finland)
                in "690".."699" -> c.getString(R.string.country_china)
                in "700".."709" -> c.getString(R.string.country_norway)
                in "730".."739" -> c.getString(R.string.country_sweden)
                in "754".."755" -> c.getString(R.string.country_canada)
                in "789".."790" -> c.getString(R.string.country_brazil)
                in "800".."839" -> c.getString(R.string.country_italy)
                in "840".."849" -> c.getString(R.string.country_spain)
                in "868".."869" -> c.getString(R.string.country_turkey)
                "387" -> c.getString(R.string.country_bosnia_herzegovina)
                "380" -> c.getString(R.string.country_bulgaria)
                "383" -> c.getString(R.string.country_slovenia)
                "385" -> c.getString(R.string.country_croatia)
                "389" -> c.getString(R.string.country_montenegro)
                "470" -> c.getString(R.string.country_kyrgyzstan)
                "471" -> c.getString(R.string.country_taiwan)
                "474" -> c.getString(R.string.country_estonia)
                "475" -> c.getString(R.string.country_latvia)
                "476" -> c.getString(R.string.country_azerbaijan)
                "477" -> c.getString(R.string.country_lithuania)
                "478" -> c.getString(R.string.country_uzbekistan)
                "479" -> c.getString(R.string.country_sri_lanka)
                "480" -> c.getString(R.string.country_philippines)
                "481" -> c.getString(R.string.country_belarus)
                "482" -> c.getString(R.string.country_ukraine)
                "483" -> c.getString(R.string.country_turkmenistan)
                "484" -> c.getString(R.string.country_moldova)
                "485" -> c.getString(R.string.country_armenia)
                "486" -> c.getString(R.string.country_georgia)
                "487" -> c.getString(R.string.country_kazakhstan)
                "488" -> c.getString(R.string.country_tajikistan)
                "489" -> c.getString(R.string.country_hong_kong)
                "528" -> c.getString(R.string.country_lebanon)
                "529" -> c.getString(R.string.country_cyprus)
                "530" -> c.getString(R.string.country_albania)
                "531" -> c.getString(R.string.country_macedonia)
                "535" -> c.getString(R.string.country_malta)
                "539" -> c.getString(R.string.country_ireland)
                "560" -> c.getString(R.string.country_portugal)
                "569" -> c.getString(R.string.country_iceland)
                "590" -> c.getString(R.string.country_poland)
                "594" -> c.getString(R.string.country_romania)
                "599" -> c.getString(R.string.country_hungary)
                "603" -> c.getString(R.string.country_ghana)
                "604" -> c.getString(R.string.country_senegal)
                "608" -> c.getString(R.string.country_bahrain)
                "609" -> c.getString(R.string.country_mauritius)
                "611" -> c.getString(R.string.country_morocco)
                "613" -> c.getString(R.string.country_algeria)
                "615" -> c.getString(R.string.country_nigeria)
                "616" -> c.getString(R.string.country_kenya)
                "618" -> c.getString(R.string.country_ivory_coast)
                "619" -> c.getString(R.string.country_tunisia)
                "620" -> c.getString(R.string.country_tanzania)
                "621" -> c.getString(R.string.country_syria)
                "622" -> c.getString(R.string.country_egypt)
                "623" -> c.getString(R.string.country_brunei)
                "624" -> c.getString(R.string.country_libya)
                "625" -> c.getString(R.string.country_jordan)
                "626" -> c.getString(R.string.country_iran)
                "627" -> c.getString(R.string.country_kuwait)
                "628" -> c.getString(R.string.country_saudi_arabia)
                "629" -> c.getString(R.string.country_emirates)
                "740" -> c.getString(R.string.country_guatemala)
                "741" -> c.getString(R.string.country_el_salvador)
                "742" -> c.getString(R.string.country_honduras)
                "743" -> c.getString(R.string.country_nicaragua)
                "744" -> c.getString(R.string.country_costa_rica)
                "745" -> c.getString(R.string.country_panama)
                "746" -> c.getString(R.string.country_dominican)
                "750" -> c.getString(R.string.country_mexico)
                "759" -> c.getString(R.string.country_venezuela)
                "773" -> c.getString(R.string.country_uruguay)
                "775" -> c.getString(R.string.country_peru)
                "777" -> c.getString(R.string.country_bolivia)
                "780" -> c.getString(R.string.country_chile)
                "784" -> c.getString(R.string.country_paraguay)
                "786" -> c.getString(R.string.country_ecuador)
                "884" -> c.getString(R.string.country_cambodia)
                "850" -> c.getString(R.string.country_cuba)
                "859" -> c.getString(R.string.country_czech)
                "858" -> c.getString(R.string.country_slovakia)
                "860" -> c.getString(R.string.country_serbia)
                "865" -> c.getString(R.string.country_mongolia)
                "867" -> c.getString(R.string.country_north_korea)
                "880" -> c.getString(R.string.country_south_korea)
                "885" -> c.getString(R.string.country_thailand)
                "888" -> c.getString(R.string.country_singapore)
                "890" -> c.getString(R.string.country_india)
                "893" -> c.getString(R.string.country_vietnam)
                "896" -> c.getString(R.string.country_pakistan)
                "899" -> c.getString(R.string.country_indonesia)
                "955" -> c.getString(R.string.country_malaysia)
                "729", "871" -> c.getString(R.string.pigs)

                else -> c.getString(R.string.unknown_country)
            }

        } else {
            return c.getString(R.string.unknown_country)
        }
    }
}